name: Code check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  code-check:
    runs-on: ubuntu-20.04
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.0
        with:
          node-version: 16

      - name: Install dependencies
        run: "yarn"

      - name: Lint
        run: "yarn lint:root"

      - name: Test compile
        run: "yarn build:test"
